name: Android Debug Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Android NDK
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-35"
          sdkmanager "build-tools;35.0.0"
          sdkmanager "ndk;27.0.12077973"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Find APK
        run: find . -type f -name "*-debug.apk"

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Debug-APK
          path: |
            **/build/outputs/apk/debug/*-debug.apk
          if-no-files-found: error
          retention-days: 7
